name: flick_video_player
description: Flick Video Player is a video player for flutter. The video_player plugin gives low level access for the video playback.
repository: https://github.com/GeekyAnts/flick-video-player
homepage: https://github.com/GeekyAnts/flick-video-player

version: 0.6.0

environment:
  sdk: '>=2.17.0 <3.0.0'



dependencies:

  flutter:
    sdk: flutter

  provider: ^6.0.1
  video_player: ^2.6.0
  wakelock: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
